import {Dimensions} from 'react-native';
export const theme = {
  colors: {
    primary: '#0E4E82',
    active: '#04950A',
    info: '#F5F5F5',
    white: '#FFFFFF',
    black: '#000000',
    background: '#f9fcf7',
    link: '#1E88E5',
    disabled: '#6c757d',
    subtitle:'#616161',
    shadesOfGray: '#333333',
    darkText: '#212121',
    secondarySearch: '#49454F',
    secondarySort: "#191919",
    card1: "#5A9BCF",
    card2: "#5A75CF",
    card3: "#2D8AB5",
    card4: "#32ADE6",
    iconColor: '#1C1B1F',
    price:"#0D47A1",
    remaining: '#81B683',
    essentials:'#FF9800',
    food: '#CB1D63',
    shopping: '#12568E',
    health:  '#00EEFF',
    other: '#AAAAAA',
    warning: '#FF0F0F',
    delete: '#D32F2F'
  },
  fonts: {
    regular: "Montserrat-Regular",
    bold: "Montserrat-Bold",
    semiBold: "Montserrat-SemiBold",
    medium: "Montserrat-Medium",
    light: "Montserrat-Light",
    thin: "Montserrat-Thin",
    italic: "Montserrat-Italic",
    extraBold: "Montserrat-ExtraBold",
    black: "Montserrat-Black",
  },
} as const;
